# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Hardhat full test suite CI

on:
 push:
  branches:
   - "**" # matches every branch
 pull_request:
  branches:
   - "**" # matches every branch

env:
 ALCHEMY: ${{ secrets.ALCHEMY }}
 TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}

jobs:
 test:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    node-version: [16.13.1]

  steps:
   - uses: actions/checkout@v2
     env:
      ALCHEMY: ${{ secrets.ALCHEMY }}
      TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
   - name: create env file
     run: |
      touch .env
      echo ALCHEMY=${{ secrets.ALCHEMY }} >> .env
      echo TEST_MNEMONIC=${{ secrets.TEST_MNEMONIC }} >> .env
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v2
     with:
      node-version: ${{ matrix.node-version }}
   - run: cd contracts
   - run: npm install
   - run: npm run compile
   - run: npx hardhat test ./test/BlackScholes.ts
     # We are currently not running integration tests due to a hardhat prvider error
     # the error only occurs in GitHub Actions VMs
